### ISSUE TITLE
Lock Routes

### ISSUE THREAD

**Issue by AlexHg** [Tony133/Symfony5APIBoilerplateJWT#8]
Hey there! :) 
What is the best method to lock routes with authorization bearer token? 
Ive tried many times with not successfuly results :s 

Ive tried: 
+ Secure the controller class with annotations: @Security("is_granted('ROLE_APP_USER')")
+ Set access_control for api routes

Full authentication is required to access this resource. (401 Unauthorized)

**Comment by Tony133** [comment]
Hi :-)

But I don't want it to be a symfony security bug, since since version 5.0.7 there are some problems

Did you do this step?

Generate the SSH keys
```
	$ mkdir config/jwt
	$ openssl genrsa -out config/jwt/private.pem -aes256 4096
	$ openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
```

and check the .env file on JWT_PASSPHRASE if it is the same as what you entered doing the 
Generate the SSH keys


To protect the routes with jwt tokens you can use as you said

access_control on the security.yml file something like:

```
access_control:
     - {path: ^/api/ secure, roles: ROLE_ADMIN}
```

or the @security annotations or voters --> https://symfony.com/doc/current/security/voters.html

if you want to do something more complex use the voters which would be an alternative to the symfony ACL which they have now removed from symfony 4 onwards which was this: https://symfony.com/doc/current/security/acl.html

**Comment by AlexHg** [comment]
"Did you do this step?
Generate the SSH keys"

Yes, i did generate the keys and used the security annotation

I dont wanna create a complex symfony structure but mi trying create a 3 project bases app (1 symfony api, 1 symfony admin and ionic app) 
This project is for api rest.

I tink is good idea create a symfony 4 api project instead v5 by these problems or what do you think?

Think you for response:)

**Comment by Tony133** [comment]
You're welcome, it's nothing

However if you want to use this project with symfony 4 LTS , put the 6.0.0 tag like this:
```
composer create-project tony133/symfony5-api-boilerplate-jwt  My_project "6.0.0"
```
I always create a tag for each previous symfony version when I switch to the new one

**Comment by Tony133** [comment]
created a protected resource, for example working with the symfony 5.1 version
